### PR TITLE
Do not return highest priority format immediately when catch-all is dete...

### PR DESCRIPTION
**Pull request by teohhanhui**
...cted

Related to issue 372 of FOSRestBundle: https://github.com/FriendsOfSymfony/FOSRestBundle/issues/372

From the HTTP/1.1 spec (http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html):

Media ranges can be overridden by more specific media ranges or specific media types. If more than one media range applies to a given type, the most specific reference has precedence. For example,

```
   Accept: text/*, text/html, text/html;level=1, */*
```

have the following precedence:

```
   1) text/html;level=1
   2) text/html
   3) text/*
   4) */*
```

### CODE REVIEW

**Comment by lsmith77** [comment]
hmm i am a bit hesitant to mess with this .. there are obviously still a lot of limitations in this solution (for example `text/*` etc is not supported). so there will one day hopefully be bigger changes, i am just unsure if i should allow smaller incremental changes, since these can have quite tricky behavior changes for people to keep up with.

either way please also provide a test case for this.

**Comment by lsmith77** [comment]
btw .. please also fix the tests

**Comment by lsmith77** [comment]
@willdurand you might be interested in this change as well

**Comment by willdurand** [comment]
Yup, I will check this edge case in [Negotiation](https://github.com/willdurand/Negotiation).

**Comment by willdurand** [comment]
@lsmith77 https://github.com/willdurand/Negotiation/commit/29ed0cab65ce352c6ff1cde0b053c91c8a6b2bb6

**Pull request merged**
