### PR TITLE
Use negotiator lib

### PR DESCRIPTION
**Pull request by lsmith77**
@willdurand wdyt?

Then again .. maybe it would be better to move the entire Symfony2 specific code to FOSRestBundle at this point.

### CODE REVIEW

**Comment by stof** [comment]
I agree about moving all Symfony2 code to the bundle as the content negotiation is now standalone

**Comment by lsmith77** [comment]
the question is what to do with the Codes class and the Decoders .. leave them here?

**Comment by stof** [comment]
Maybe they can be moved back to FOSRestBundle ?

**Comment by lsmith77** [comment]
sure they could .. then again they would then be truly independent of symfony as well ..

**Comment by willdurand** [comment]
So, the idea is to decide whether to get rid of this lib or not?

**Comment by lsmith77** [comment]
right ..

**Comment by willdurand** [comment]
I personally don't mind. Keeping this lib would ensure BC in case people rely exclusively on it.

**Comment by willdurand** [comment]
So I thought a bit more about this change, and I would move all Symfony2 related stuff to the bundle itself, and keep Codes and Decoders into this lib for now.

**Pull request closed without merging**
